In [3]:
import pandas as pd
from gssutils import pathify

df = pd.read_csv("./example1/probation-caseload_all-supervision.csv")

df.head()

,Probation Area,Area,Value,Period,Measure Type,Sex
0,NPS Midlands,E92000001,16721,day/2018-03-31,Count of offenders supervised,M
1,"Bristol, Gloucestershire, Somerset and Wiltshi...",E92000001,5576,day/2018-03-31,Count of offenders supervised,M
2,Cheshire and Greater Manchester CRC,E92000001,10483,day/2018-03-31,Count of offenders supervised,M
3,Durham Tees Valley CRC,E92000001,642,day/2018-03-31,Count of offenders supervised,F
4,"Derbyshire, Leicestershire, Nottinghamshire an...",E92000001,1163,day/2018-03-31,Count of offenders supervised,F

In [14]:

for col in ["Area"]:
    
    d = {
        "Label":[],
        "Notation":[],
        "Parent Notation":[],
        "Sort Priority":[],
        "Description":[]
    }
    for v in list(df[col].unique()):
        
        if col == "Sex":
            lookup = {"M": "Male", "F": "Female"}
            d["Label"].append(lookup[v])
            d["Notation"].append(v)
        else:
            d["Label"].append(v)
            d["Notation"].append(v)
        
        d["Parent Notation"].append("")
        d["Sort Priority"].append("")
        d["Description"].append("")
        
        pd.DataFrame.from_dict(d).to_csv(pathify(col)+".csv", index=False)